version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - 3434:3000
    env_file:
      - .env
    command: sh -c "npm run dev"
